-- Oracle 19c DDL script for the TasKitto example (tables + foreign keys + views).
--
-- Dialect notes (see TEFOracleDBEngineType in Source/EF/EF.DB.pas):
--   * Boolean columns (IS_ACTIVE / MUST_CHANGE_PASSWORD) use NUMBER(1) with 1/0
--     (Oracle pre-23c has no native BOOLEAN). The %DB.TRUE% / %DB.FALSE% macros
--     expand to 1 / 0 on Oracle, so Kitto.Auth.DB / Kitto.AccessControl.DB SQL
--     works natively.
--   * 'time' (START_TIME / END_TIME) has no Oracle equivalent: it is stored in a
--     DATE holding only the time-of-day (KittoX ExpandDateTimeFrom).
--   * varchar -> VARCHAR2; integer -> NUMBER(10); float -> FLOAT.
--   * Identifiers are unquoted (Oracle folds them to upper case, matching the
--     metadata). Recommended DB character set: AL32UTF8.
--
-- Dashboard views translate the SQL Server / PostgreSQL date functions to Oracle:
--   GETDATE() / CURRENT_DATE          -> SYSDATE (TRUNC(SYSDATE) for date only)
--   DATEFROMPARTS(YEAR,MONTH,1)       -> TRUNC(SYSDATE,'MM')  (first day of month)
--   DATEADD(MONTH, 1, x)              -> ADD_MONTHS(x, 1)
--   DATEADD(DAY, n, x)                -> x + n
--   DATEDIFF(MINUTE, s, e) / 60       -> (e - s) * 24     (DATE diff = fractional days)
--   ISNULL(x, 0)                      -> NVL(x, 0)
--   subquery with no FROM             -> FROM DUAL
--
-- Primary keys are string ids (no auto-increment), so no sequences/identity are
-- needed. Run this as the schema owner, then run TasKitto_Oracle_Data.sql.

/******************** TABLES **********************/

CREATE TABLE KITTO_USERS
(
  USER_NAME            VARCHAR2(32)  NOT NULL,
  PASSWORD_HASH        VARCHAR2(60),
  IS_ACTIVE            NUMBER(1) DEFAULT 1 NOT NULL CHECK (IS_ACTIVE IN (0, 1)),
  FIRST_NAME           VARCHAR2(50),
  LAST_NAME            VARCHAR2(50),
  EMAIL_ADDRESS        VARCHAR2(100) NOT NULL,
  MUST_CHANGE_PASSWORD NUMBER(1) DEFAULT 0 NOT NULL CHECK (MUST_CHANGE_PASSWORD IN (0, 1)),
  CONSTRAINT PK_KITTO_USERS PRIMARY KEY (USER_NAME)
);

-- Standard KittoX ACL tables, read by both AccessControl: DB (TKDBAccessController)
-- and AccessControl: JWT (TKJWTAccessController, snapshotted at login).
-- Schema is fixed by the default SQL queries in Source/Kitto.AccessControl.DB.pas;
-- override via AccessControl/ReadPermissionsCommandText / ReadRolesCommandText if needed.

CREATE TABLE KITTO_USER_ROLES
(
  USER_NAME VARCHAR2(50) NOT NULL,
  ROLE_NAME VARCHAR2(50) NOT NULL,
  CONSTRAINT PK_KITTO_USER_ROLES PRIMARY KEY (USER_NAME, ROLE_NAME)
);

CREATE TABLE KITTO_PERMISSIONS
(
  RESOURCE_URI_PATTERN VARCHAR2(200) NOT NULL,
  GRANTEE_NAME         VARCHAR2(50)  NOT NULL,
  ACCESS_MODES         VARCHAR2(100) NOT NULL,
  GRANT_VALUE          VARCHAR2(50)  NOT NULL,
  CONSTRAINT PK_KITTO_PERMISSIONS PRIMARY KEY (RESOURCE_URI_PATTERN, GRANTEE_NAME, ACCESS_MODES)
);

CREATE TABLE ACTIVITY_TYPE
(
  TYPE_ID   VARCHAR2(32) NOT NULL,
  TYPE_NAME VARCHAR2(20) NOT NULL,
  CONSTRAINT PK_ACTIVITY_TYPE PRIMARY KEY (TYPE_ID)
);

CREATE TABLE CUSTOMER
(
  CUSTOMER_ID   VARCHAR2(32) NOT NULL,
  CUSTOMER_NAME VARCHAR2(40) NOT NULL,
  ADDRESS       VARCHAR2(60),
  CITY          VARCHAR2(60),
  PHONE         VARCHAR2(20),
  EMAIL         VARCHAR2(60),
  STATUS        VARCHAR2(10),
  CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE EMPLOYEE
(
  EMPLOYEE_ID   VARCHAR2(32) NOT NULL,
  EMPLOYEE_NAME VARCHAR2(40) NOT NULL,
  EMPLOYEE_TYPE VARCHAR2(20),
  CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEE_ID)
);

CREATE TABLE OPERATOR_ROLE
(
  ROLE_ID   VARCHAR2(32) NOT NULL,
  ROLE_NAME VARCHAR2(20) NOT NULL,
  FEE       FLOAT,
  CONSTRAINT PK_OPERATOR_ROLE PRIMARY KEY (ROLE_ID)
);

CREATE TABLE PROJECT
(
  PROJECT_ID   VARCHAR2(32) NOT NULL,
  PROJECT_NAME VARCHAR2(40) NOT NULL,
  CUSTOMER_ID  VARCHAR2(32) NOT NULL,
  STATUS       VARCHAR2(12),
  CONSTRAINT PK_PROJECT PRIMARY KEY (PROJECT_ID)
);

CREATE TABLE PHASE
(
  PHASE_ID    VARCHAR2(32) NOT NULL,
  PHASE_NAME  VARCHAR2(40) NOT NULL,
  PROJECT_ID  VARCHAR2(32) NOT NULL,
  START_DATE  DATE,
  END_DATE    DATE,
  STATUS      VARCHAR2(12),
  CONSTRAINT PK_PHASE PRIMARY KEY (PHASE_ID)
);

CREATE TABLE ACTIVITY
(
  ACTIVITY_ID   VARCHAR2(32) NOT NULL,
  DESCRIPTION   VARCHAR2(80) NOT NULL,
  PHASE_ID      VARCHAR2(32) NOT NULL,
  EMPLOYEE_ID   VARCHAR2(32) NOT NULL,
  ROLE_ID       VARCHAR2(32) NOT NULL,
  TYPE_ID       VARCHAR2(32) NOT NULL,
  ACTIVITY_DATE DATE         NOT NULL,
  START_TIME    DATE,
  END_TIME      DATE,
  STATUS        VARCHAR2(12),
  CONSTRAINT PK_ACTIVITY PRIMARY KEY (ACTIVITY_ID)
);

/******************** FOREIGN KEYS *******************/

ALTER TABLE PROJECT ADD CONSTRAINT DT_PROJECT_CUSTOMER
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID);

ALTER TABLE PHASE ADD CONSTRAINT DT_PHASE_PROJECT
  FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID);

ALTER TABLE ACTIVITY ADD CONSTRAINT DT_ACTIVITY_PHASE
  FOREIGN KEY (PHASE_ID) REFERENCES PHASE (PHASE_ID);

ALTER TABLE ACTIVITY ADD CONSTRAINT FK_ACTIVITY_ACTIVITY_TYPE
  FOREIGN KEY (TYPE_ID) REFERENCES ACTIVITY_TYPE (TYPE_ID);

ALTER TABLE ACTIVITY ADD CONSTRAINT FK_ACTIVITY_OPERATOR_ROLE
  FOREIGN KEY (ROLE_ID) REFERENCES OPERATOR_ROLE (ROLE_ID);

ALTER TABLE ACTIVITY ADD CONSTRAINT FK_ACTIVITY_EMPLOYEE
  FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID);

/********************* VIEWS **********************/

-- Average activity duration (hours) per day.
CREATE VIEW ACTIVITY_BY_DATE (ACTIVITY_DATE, DURATION, ACTIVITIES) AS
SELECT
  A.ACTIVITY_DATE,
  CAST(AVG((A.END_TIME - A.START_TIME) * 24) AS NUMBER(8,4)) AS DURATION,
  COUNT(*) AS ACTIVITIES
FROM ACTIVITY A
GROUP BY A.ACTIVITY_DATE;

-- Total hours per activity type, used by the Hours-by-Type pie on the
-- dashboard. SUM (not AVG) so the pie reflects share of total time per type.
CREATE VIEW ACTIVITY_BY_TYPE (DURATION, TYPE_NAME) AS
SELECT
  CAST(SUM((A.END_TIME - A.START_TIME) * 24) AS NUMBER(8,2)) AS DURATION,
  T.TYPE_NAME
FROM ACTIVITY A
JOIN ACTIVITY_TYPE T ON A.TYPE_ID = T.TYPE_ID
GROUP BY T.TYPE_NAME;

-- Current-month activity count and hours by status.
CREATE VIEW VW_ACTIVITY_BY_STATUS (STATUS, ACTIVITY_COUNT, TOTAL_HOURS) AS
SELECT
  A.STATUS,
  COUNT(*) AS ACTIVITY_COUNT,
  NVL(SUM((A.END_TIME - A.START_TIME) * 24), 0) AS TOTAL_HOURS
FROM ACTIVITY A
WHERE A.ACTIVITY_DATE >= TRUNC(SYSDATE, 'MM')
  AND A.ACTIVITY_DATE <  ADD_MONTHS(TRUNC(SYSDATE, 'MM'), 1)
GROUP BY A.STATUS;

-- Activity count and hours per day over a +/-15 day window around today.
CREATE VIEW VW_ACTIVITY_DAILY_RANGE (ACTIVITY_DATE, ACTIVITY_COUNT, TOTAL_HOURS) AS
SELECT
  A.ACTIVITY_DATE,
  COUNT(*) AS ACTIVITY_COUNT,
  NVL(SUM((A.END_TIME - A.START_TIME) * 24), 0) AS TOTAL_HOURS
FROM ACTIVITY A
WHERE A.ACTIVITY_DATE >= TRUNC(SYSDATE) - 15
  AND A.ACTIVITY_DATE <= TRUNC(SYSDATE) + 15
GROUP BY A.ACTIVITY_DATE;

-- Single-row KPI card values for the current month.
CREATE VIEW VW_KPI_MONTHLY (ACTIVITY_COUNT, TOTAL_HOURS, ACTIVE_PROJECTS, ACTIVE_CUSTOMERS) AS
SELECT
  (SELECT COUNT(*) FROM ACTIVITY
   WHERE ACTIVITY_DATE >= TRUNC(SYSDATE, 'MM')
     AND ACTIVITY_DATE <  ADD_MONTHS(TRUNC(SYSDATE, 'MM'), 1)
  ) AS ACTIVITY_COUNT,
  (SELECT NVL(SUM((END_TIME - START_TIME) * 24), 0) FROM ACTIVITY
   WHERE ACTIVITY_DATE >= TRUNC(SYSDATE, 'MM')
     AND ACTIVITY_DATE <  ADD_MONTHS(TRUNC(SYSDATE, 'MM'), 1)
  ) AS TOTAL_HOURS,
  (SELECT COUNT(*) FROM PROJECT WHERE STATUS = 'Open') AS ACTIVE_PROJECTS,
  (SELECT COUNT(DISTINCT P.CUSTOMER_ID)
   FROM ACTIVITY A
   INNER JOIN PHASE PH ON PH.PHASE_ID = A.PHASE_ID
   INNER JOIN PROJECT P ON P.PROJECT_ID = PH.PROJECT_ID
   WHERE A.ACTIVITY_DATE >= TRUNC(SYSDATE, 'MM')
     AND A.ACTIVITY_DATE <  ADD_MONTHS(TRUNC(SYSDATE, 'MM'), 1)
  ) AS ACTIVE_CUSTOMERS
FROM DUAL;
