/******************** TABLES **********************/
-- IS_ACTIVE / MUST_CHANGE_PASSWORD use the native BIT type. The %DB.TRUE% / %DB.FALSE%
-- macros expand to the literal 1 / 0 in the SQL Server dialect (see
-- TEFSQLServerDBEngineType.GetBoolTrueLiteral in EF.DB.pas), so the SQL queries
-- from Kitto.Auth.DB / Kitto.AccessControl.DB work natively. The same data files
-- (1 / 0 in the INSERT statements) bind to BIT and to the legacy SMALLINT columns
-- transparently, so existing apps that still use SMALLINT are not affected.
CREATE TABLE KITTO_USERS
(
  USER_NAME varchar(32) NOT NULL,
  PASSWORD_HASH varchar(60),
  IS_ACTIVE bit NOT NULL DEFAULT 1,
  FIRST_NAME varchar(50),
  LAST_NAME varchar(50),
  EMAIL_ADDRESS varchar(100) NOT NULL,
  MUST_CHANGE_PASSWORD bit NOT NULL DEFAULT 0,
  CONSTRAINT PK_KITTO_USERS PRIMARY KEY (USER_NAME)
);

-- Standard KittoX ACL tables, read by both AccessControl: DB (TKDBAccessController)
-- and AccessControl: JWT (TKJWTAccessController, snapshotted at login).
-- Schema is fixed by the default SQL queries in Source/Kitto.AccessControl.DB.pas;
-- override via AccessControl/ReadPermissionsCommandText / ReadRolesCommandText if needed.

CREATE TABLE KITTO_USER_ROLES
(
  USER_NAME varchar(50) NOT NULL,
  ROLE_NAME varchar(50) NOT NULL,
  CONSTRAINT PK_KITTO_USER_ROLES PRIMARY KEY (USER_NAME, ROLE_NAME)
);

CREATE TABLE KITTO_PERMISSIONS
(
  RESOURCE_URI_PATTERN varchar(200) NOT NULL,
  GRANTEE_NAME varchar(50) NOT NULL,
  ACCESS_MODES varchar(100) NOT NULL,
  GRANT_VALUE varchar(50) NOT NULL,
  CONSTRAINT PK_KITTO_PERMISSIONS PRIMARY KEY (RESOURCE_URI_PATTERN, GRANTEE_NAME, ACCESS_MODES)
);
CREATE TABLE ACTIVITY
(
  ACTIVITY_ID varchar(32) NOT NULL,
  DESCRIPTION varchar(80) NOT NULL,
  PHASE_ID varchar(32) NOT NULL,
  EMPLOYEE_ID varchar(32) NOT NULL,
  ROLE_ID varchar(32) NOT NULL,
  TYPE_ID varchar(32) NOT NULL,
  ACTIVITY_DATE date NOT NULL,
  START_TIME time,
  END_TIME time,
  STATUS varchar(12),
  CONSTRAINT PK_ACTIVITY PRIMARY KEY (ACTIVITY_ID)
);

CREATE TABLE ACTIVITY_TYPE
(
  TYPE_ID varchar(32) NOT NULL,
  TYPE_NAME varchar(20) NOT NULL,
  CONSTRAINT PK_ACTIVITY_TYPE PRIMARY KEY (TYPE_ID)
);

CREATE TABLE CUSTOMER
(
  CUSTOMER_ID varchar(32) NOT NULL,
  CUSTOMER_NAME varchar(40) NOT NULL,
  ADDRESS varchar(60),
  CITY varchar(60),
  PHONE varchar(20),
  EMAIL varchar(60),
  STATUS varchar(10),
  CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID)
);
CREATE TABLE EMPLOYEE
(
  EMPLOYEE_ID varchar(32) NOT NULL,
  EMPLOYEE_NAME varchar(40) NOT NULL,
  EMPLOYEE_TYPE varchar(20),
  CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEE_ID)
);
CREATE TABLE OPERATOR_ROLE
(
  ROLE_ID varchar(32) NOT NULL,
  ROLE_NAME varchar(20) NOT NULL,
  FEE float,
  CONSTRAINT PK_OPERATOR_ROLE PRIMARY KEY (ROLE_ID)
);
CREATE TABLE PHASE
(
  PHASE_ID varchar(32) NOT NULL,
  PHASE_NAME varchar(40) NOT NULL,
  PROJECT_ID varchar(32) NOT NULL,
  START_DATE date,
  END_DATE date,
  STATUS varchar(12),
  CONSTRAINT PK_PHASE PRIMARY KEY (PHASE_ID)
);
CREATE TABLE PROJECT
(
  PROJECT_ID varchar(32) NOT NULL,
  PROJECT_NAME varchar(40) NOT NULL,
  CUSTOMER_ID varchar(32) NOT NULL,
  STATUS varchar(12),
  CONSTRAINT PK_PROJECT PRIMARY KEY (PROJECT_ID)
);

ALTER TABLE ACTIVITY ADD CONSTRAINT DT_ACTIVITY_PHASE
  FOREIGN KEY (PHASE_ID) REFERENCES PHASE (PHASE_ID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE ACTIVITY ADD CONSTRAINT FK_ACTIVITY_ACTIVITY_TYPE
  FOREIGN KEY (TYPE_ID) REFERENCES ACTIVITY_TYPE (TYPE_ID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE ACTIVITY ADD CONSTRAINT FK_ACTIVITY_EMPLOYEE
  FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE ACTIVITY ADD CONSTRAINT FK_ACTIVITY_OPERATOR_ROLE
  FOREIGN KEY (ROLE_ID) REFERENCES OPERATOR_ROLE (ROLE_ID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE PHASE ADD CONSTRAINT DT_PHASE_PROJECT
  FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE PROJECT ADD CONSTRAINT DT_PROJECT_CUSTOMER
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID) ON UPDATE NO ACTION ON DELETE NO ACTION;


