/********************* ROLES **********************/

/********************* UDFS ***********************/

/****************** SEQUENCES ********************/

/******************** DOMAINS *********************/

/******************* PROCEDURES ******************/

/******************** TABLES **********************/

CREATE TABLE ACTIVITY
(
  ACTIVITY_ID varchar(32) NOT NULL,
  DESCRIPTION varchar(80) NOT NULL,
  PHASE_ID varchar(32) NOT NULL,
  EMPLOYEE_ID varchar(32) NOT NULL,
  ROLE_ID varchar(32) NOT NULL,
  TYPE_ID varchar(32) NOT NULL,
  ACTIVITY_DATE date NOT NULL,
  START_TIME time,
  END_TIME time,
  STATUS varchar(12),
  CONSTRAINT PK_ACTIVITY PRIMARY KEY (ACTIVITY_ID)
);
CREATE TABLE ACTIVITY_TYPE
(
  TYPE_ID varchar(32) NOT NULL,
  TYPE_NAME varchar(20) NOT NULL,
  CONSTRAINT PK_ACTIVITY_TYPE PRIMARY KEY (TYPE_ID)
);
CREATE TABLE CUSTOMER
(
  CUSTOMER_ID varchar(32) NOT NULL,
  CUSTOMER_NAME varchar(40) NOT NULL,
  ADDRESS varchar(60),
  CITY varchar(60),
  PHONE varchar(20),
  EMAIL varchar(60),
  STATUS varchar(10),
  CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID)
);
CREATE TABLE EMPLOYEE
(
  EMPLOYEE_ID varchar(32) NOT NULL,
  EMPLOYEE_NAME varchar(40) NOT NULL,
  EMPLOYEE_TYPE varchar(20),
  CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEE_ID)
);
-- IS_ACTIVE / MUST_CHANGE_PASSWORD use the native BOOLEAN type introduced in
-- Firebird 3.0. The %DB.TRUE% / %DB.FALSE% macros expand to the literal TRUE / FALSE
-- in the Firebird dialect (see TEFDBEngineType.GetBoolTrueLiteral in EF.DB.pas), so
-- the SQL queries from Kitto.Auth.DB / Kitto.AccessControl.DB work natively.
-- Apps that must run against Firebird 2.5 or earlier need to substitute SMALLINT here
-- and override the boolean macros via descendant TEFDBEngineType.
CREATE TABLE KITTO_USERS
(
  USER_NAME varchar(32) NOT NULL,
  PASSWORD_HASH varchar(60),
  IS_ACTIVE boolean DEFAULT TRUE NOT NULL,
  FIRST_NAME varchar(50),
  LAST_NAME varchar(50),
  EMAIL_ADDRESS varchar(100) NOT NULL,
  MUST_CHANGE_PASSWORD boolean DEFAULT FALSE NOT NULL,
  CONSTRAINT PK_KITTO_USERS PRIMARY KEY (USER_NAME)
);

-- Standard KittoX ACL tables, read by both AccessControl: DB (TKDBAccessController)
-- and AccessControl: JWT (TKJWTAccessController, snapshotted at login).
-- Schema is fixed by the default SQL queries in Source/Kitto.AccessControl.DB.pas;
-- override via AccessControl/ReadPermissionsCommandText / ReadRolesCommandText if needed.

CREATE TABLE KITTO_USER_ROLES
(
  USER_NAME varchar(50) NOT NULL,
  ROLE_NAME varchar(50) NOT NULL,
  CONSTRAINT PK_KITTO_USER_ROLES PRIMARY KEY (USER_NAME, ROLE_NAME)
);

CREATE TABLE KITTO_PERMISSIONS
(
  RESOURCE_URI_PATTERN varchar(200) NOT NULL,
  GRANTEE_NAME varchar(50) NOT NULL,
  ACCESS_MODES varchar(100) NOT NULL,
  GRANT_VALUE varchar(50) NOT NULL,
  CONSTRAINT PK_KITTO_PERMISSIONS PRIMARY KEY (RESOURCE_URI_PATTERN, GRANTEE_NAME, ACCESS_MODES)
);

CREATE TABLE OPERATOR_ROLE
(
  ROLE_ID varchar(32) NOT NULL,
  ROLE_NAME varchar(20) NOT NULL,
  FEE float,
  CONSTRAINT PK_OPERATOR_ROLE PRIMARY KEY (ROLE_ID)
);
CREATE TABLE PHASE
(
  PHASE_ID varchar(32) NOT NULL,
  PHASE_NAME varchar(40) NOT NULL,
  PROJECT_ID varchar(32) NOT NULL,
  START_DATE date,
  END_DATE date,
  STATUS varchar(12),
  CONSTRAINT PK_PHASE PRIMARY KEY (PHASE_ID)
);
CREATE TABLE PROJECT
(
  PROJECT_ID varchar(32) NOT NULL,
  PROJECT_NAME varchar(40) NOT NULL,
  CUSTOMER_ID varchar(32) NOT NULL,
  STATUS varchar(12),
  CONSTRAINT PK_PROJECT PRIMARY KEY (PROJECT_ID)
);
/*******************************************************************************
 * Foreign Key Constraints
 * -----------------------
 * Extracted at 22/10/2011 0.54.20
 ******************************************************************************/

ALTER TABLE PROJECT ADD CONSTRAINT DT_PROJECT_CUSTOMER
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER
  (CUSTOMER_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

ALTER TABLE PHASE ADD CONSTRAINT DT_PHASE_PROJECT
  FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT
  (PROJECT_ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

ALTER TABLE ACTIVITY ADD CONSTRAINT DT_ACTIVITY_PHASE
  FOREIGN KEY (PHASE_ID) REFERENCES PHASE
  (PHASE_ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

ALTER TABLE ACTIVITY ADD CONSTRAINT FK_ACTIVITY_ACTIVITY_TYPE 
  FOREIGN KEY (TYPE_ID) REFERENCES ACTIVITY_TYPE
  (TYPE_ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

ALTER TABLE ACTIVITY ADD CONSTRAINT FK_ACTIVITY_OPERATOR_ROLE 
  FOREIGN KEY (ROLE_ID) REFERENCES OPERATOR_ROLE
  (ROLE_ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

ALTER TABLE ACTIVITY ADD CONSTRAINT FK_ACTIVITY_EMPLOYEE 
  FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE
  (EMPLOYEE_ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;
/********************* VIEWS **********************/

CREATE VIEW ACTIVITY_BY_DATE (ACTIVITY_DATE, DURATION, ACTIVITIES)
AS  
SELECT
  A.ACTIVITY_DATE, 
  CAST(AVG(DATEDIFF(millisecond, A.START_TIME, A.END_TIME) / CAST(3600000 AS FLOAT)) AS DECIMAL(8,4)) DURATION, 
  COUNT(*) ACTIVITIES
FROM ACTIVITY A
GROUP BY
  ACTIVITY_DATE
;
-- Total hours per activity type, used by the Hours-by-Type pie on the
-- dashboard. SUM (not AVG) so the pie reflects share of total time per
-- type — AVG of per-activity duration is ~uniform across types and would
-- produce equal slices.
CREATE VIEW ACTIVITY_BY_TYPE (DURATION, TYPE_NAME)
AS
SELECT
  CAST(SUM(DATEDIFF(millisecond, A.START_TIME, A.END_TIME) / CAST(3600000 AS FLOAT)) AS DECIMAL(8,2)) DURATION,
  T.TYPE_NAME
FROM ACTIVITY A
join ACTIVITY_TYPE T on A.TYPE_ID = T.TYPE_ID
GROUP BY
  T.TYPE_NAME
;

-- Dashboard views — same shape as the SQL Server / PostgreSQL counterparts.
-- Firebird translation notes:
--   GETDATE()                 → CURRENT_DATE / CURRENT_TIMESTAMP
--   ISNULL(x, 0)              → COALESCE(x, 0)
--   DATEFROMPARTS(y,m,1)      → DATEADD(DAY, -(EXTRACT(DAY FROM CURRENT_DATE) - 1), CURRENT_DATE)
--   DATEADD(MONTH, 1, x)      → DATEADD(MONTH, 1, x)  (same)
--   DATEDIFF(MINUTE, s, e)    → DATEDIFF(MINUTE, s, e)  (same; works on TIME columns)

CREATE VIEW VW_ACTIVITY_BY_STATUS (STATUS, ACTIVITY_COUNT, TOTAL_HOURS) AS
SELECT
  A.STATUS,
  COUNT(*) AS ACTIVITY_COUNT,
  COALESCE(SUM(DATEDIFF(MINUTE, A.START_TIME, A.END_TIME) / 60.0), 0) AS TOTAL_HOURS
FROM ACTIVITY A
WHERE A.ACTIVITY_DATE >= DATEADD(DAY, -(EXTRACT(DAY FROM CURRENT_DATE) - 1), CURRENT_DATE)
  AND A.ACTIVITY_DATE <  DATEADD(MONTH, 1, DATEADD(DAY, -(EXTRACT(DAY FROM CURRENT_DATE) - 1), CURRENT_DATE))
GROUP BY A.STATUS
;

CREATE VIEW VW_ACTIVITY_DAILY_RANGE (ACTIVITY_DATE, ACTIVITY_COUNT, TOTAL_HOURS) AS
SELECT
  A.ACTIVITY_DATE,
  COUNT(*) AS ACTIVITY_COUNT,
  COALESCE(SUM(DATEDIFF(MINUTE, A.START_TIME, A.END_TIME) / 60.0), 0) AS TOTAL_HOURS
FROM ACTIVITY A
WHERE A.ACTIVITY_DATE >= DATEADD(DAY, -15, CURRENT_DATE)
  AND A.ACTIVITY_DATE <= DATEADD(DAY,  15, CURRENT_DATE)
GROUP BY A.ACTIVITY_DATE
;

CREATE VIEW VW_KPI_MONTHLY (ACTIVITY_COUNT, TOTAL_HOURS, ACTIVE_PROJECTS, ACTIVE_CUSTOMERS) AS
SELECT
  (SELECT COUNT(*) FROM ACTIVITY
   WHERE ACTIVITY_DATE >= DATEADD(DAY, -(EXTRACT(DAY FROM CURRENT_DATE) - 1), CURRENT_DATE)
     AND ACTIVITY_DATE <  DATEADD(MONTH, 1, DATEADD(DAY, -(EXTRACT(DAY FROM CURRENT_DATE) - 1), CURRENT_DATE))
  ) AS ACTIVITY_COUNT,
  (SELECT COALESCE(SUM(DATEDIFF(MINUTE, START_TIME, END_TIME) / 60.0), 0) FROM ACTIVITY
   WHERE ACTIVITY_DATE >= DATEADD(DAY, -(EXTRACT(DAY FROM CURRENT_DATE) - 1), CURRENT_DATE)
     AND ACTIVITY_DATE <  DATEADD(MONTH, 1, DATEADD(DAY, -(EXTRACT(DAY FROM CURRENT_DATE) - 1), CURRENT_DATE))
  ) AS TOTAL_HOURS,
  (SELECT COUNT(*) FROM PROJECT WHERE STATUS = 'Open') AS ACTIVE_PROJECTS,
  (SELECT COUNT(DISTINCT P.CUSTOMER_ID)
   FROM ACTIVITY A
   INNER JOIN PHASE PH ON PH.PHASE_ID = A.PHASE_ID
   INNER JOIN PROJECT P ON P.PROJECT_ID = PH.PROJECT_ID
   WHERE A.ACTIVITY_DATE >= DATEADD(DAY, -(EXTRACT(DAY FROM CURRENT_DATE) - 1), CURRENT_DATE)
     AND A.ACTIVITY_DATE <  DATEADD(MONTH, 1, DATEADD(DAY, -(EXTRACT(DAY FROM CURRENT_DATE) - 1), CURRENT_DATE))
  ) AS ACTIVE_CUSTOMERS
FROM RDB$DATABASE
;

/******************* EXCEPTIONS *******************/

/******************** TRIGGERS ********************/

/******************** GRANTS ********************/
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ACTIVITY TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ACTIVITY_TYPE TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON CUSTOMER TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON EMPLOYEE TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON KITTO_USERS TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON OPERATOR_ROLE TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON PHASE TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON PROJECT TO  SYSDBA WITH GRANT OPTION;

GRANT REFERENCES, SELECT
 ON ACTIVITY_BY_DATE TO  SYSDBA WITH GRANT OPTION;

GRANT REFERENCES, SELECT
 ON ACTIVITY_BY_TYPE TO  SYSDBA WITH GRANT OPTION;
