/********************* VIEWS **********************/

CREATE VIEW ACTIVITY_BY_DATE (ACTIVITY_DATE, DURATION, ACTIVITIES)
AS 
SELECT
  A.ACTIVITY_DATE, 
  CAST(AVG(DATEDIFF(millisecond, A.START_TIME, A.END_TIME) / CAST(3600000 AS FLOAT)) AS DECIMAL(8,4)) DURATION, 
  COUNT(*) ACTIVITIES
FROM ACTIVITY A
GROUP BY
  ACTIVITY_DATE
;
GO

-- Total hours per activity type, used by the Hours-by-Type pie on the
-- dashboard. SUM (not AVG): a pie chart represents proportions, so each
-- slice must reflect the share of total hours invested per type. AVG of
-- per-activity duration would yield ~uniform values (everyone clocks
-- ~1-3h per task) and produce a near-equal-slice pie that says nothing.
CREATE VIEW ACTIVITY_BY_TYPE (DURATION, TYPE_NAME)
AS
SELECT
  CAST(SUM(DATEDIFF(millisecond, A.START_TIME, A.END_TIME) / CAST(3600000 AS FLOAT)) AS DECIMAL(8,2)) DURATION,
  T.TYPE_NAME
FROM ACTIVITY A
join ACTIVITY_TYPE T on A.TYPE_ID = T.TYPE_ID
GROUP BY 
  T.TYPE_NAME
;
GO

CREATE VIEW VW_ACTIVITY_BY_STATUS AS
SELECT
  A.STATUS,
  COUNT(*) AS ACTIVITY_COUNT,
  ISNULL(SUM(DATEDIFF(MINUTE, A.START_TIME, A.END_TIME) / 60.0), 0) AS TOTAL_HOURS
FROM ACTIVITY A
WHERE A.ACTIVITY_DATE >= DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1)
  AND A.ACTIVITY_DATE < DATEADD(MONTH, 1, DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1))
GROUP BY A.STATUS;
GO

CREATE VIEW VW_ACTIVITY_DAILY_RANGE AS
SELECT
  A.ACTIVITY_DATE,
  COUNT(*) AS ACTIVITY_COUNT,
  ISNULL(SUM(DATEDIFF(MINUTE, A.START_TIME, A.END_TIME) / 60.0), 0) AS TOTAL_HOURS
FROM ACTIVITY A
WHERE A.ACTIVITY_DATE >= DATEADD(DAY, -15, CAST(GETDATE() AS DATE))
  AND A.ACTIVITY_DATE <= DATEADD(DAY, 15, CAST(GETDATE() AS DATE))
GROUP BY A.ACTIVITY_DATE;
GO

CREATE VIEW VW_KPI_MONTHLY AS
SELECT
  (SELECT COUNT(*) FROM ACTIVITY
   WHERE ACTIVITY_DATE >= DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1)
     AND ACTIVITY_DATE < DATEADD(MONTH, 1, DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1))
  ) AS ACTIVITY_COUNT,
  (SELECT ISNULL(SUM(DATEDIFF(MINUTE, START_TIME, END_TIME) / 60.0), 0) FROM ACTIVITY
   WHERE ACTIVITY_DATE >= DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1)
     AND ACTIVITY_DATE < DATEADD(MONTH, 1, DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1))
  ) AS TOTAL_HOURS,
  (SELECT COUNT(*) FROM PROJECT WHERE STATUS = 'Open') AS ACTIVE_PROJECTS,
  (SELECT COUNT(DISTINCT P.CUSTOMER_ID)
   FROM ACTIVITY A
   INNER JOIN PHASE PH ON PH.PHASE_ID = A.PHASE_ID
   INNER JOIN PROJECT P ON P.PROJECT_ID = PH.PROJECT_ID
   WHERE A.ACTIVITY_DATE >= DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1)
     AND A.ACTIVITY_DATE < DATEADD(MONTH, 1, DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1))
  ) AS ACTIVE_CUSTOMERS;
GO